server:
  port: 8000
  compression:
    enabled: true
  error:
    whitelabel:
      enabled: false

# spring application metadata
spring:
  application:
    name: simple-fix-client

---
# spring datasource, jpa and hibernate configuration
spring:
  main:
    allow-bean-definition-overriding: true
  jpa:
    show-sql: true
    generate-ddl: true
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        "[generate_statistics]": false
        "[format_sql]": true
        type: DEBUG # reset in production
        jdbc:
          "[batch_size]": 20
        id:
          "[new_generator_mappings]": true
        connection:
          "[provider_disables_autocommit]": true
        event:
          merge:
            "[entity_copy_observer]": allow
    hibernate:
      ddl-auto: update
  datasource:
    username: postgres
    password: nurrony
    url: jdbc:postgresql://localhost/fix_oms?currentSchema=client
    driver-class-name: org.postgresql.Driver
    hikari:
      auto-commit: false
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true

---
# QuickfixJ settings
quickfixj:
  client:
    enabled: true
    jmx-enabled: true
    config: ${QUIICKFIXJ_CLIENT_CONFIG_FILE:classpath:quickfixj-client.cfg}
    message-store-factory: jdbc
    log-factory: jdbc
# QuickfixJ actuator
management:
  health:
    quickfixjclient:
      enabled: true
  endpoint:
    quickfixjclient:
      enabled: true
  endpoints:
    web:
      exposure:
        include: quickfixjclient
